"""create_therapy_summaries_table

Revision ID: 42c93e13d04e
Revises: c3d4e5f6a7b8
Create Date: 2026-06-26 18:12:50.965732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""create_therapy_summaries_table

Revision ID: 42c93e13d04e
Revises: c3d4e5f6a7b8
Create Date: 2026-06-26 18:12:50.965732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42c93e13d04e'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('therapy_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('therapy_type', sa.String(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('summaries', sa.JSON(), nullable=False),
    sa.Column('reports_hash', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('truncation_type', sa.String(), nullable=True),
    sa.Column('skipped_report_dates', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_therapy_summaries_id'), 'therapy_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_therapy_summaries_reports_hash'), 'therapy_summaries', ['reports_hash'], unique=False)
    op.create_index(op.f('ix_therapy_summaries_student_id'), 'therapy_summaries', ['student_id'], unique=False)
    op.create_index(op.f('ix_therapy_summaries_therapy_type'), 'therapy_summaries', ['therapy_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_therapy_summaries_therapy_type'), table_name='therapy_summaries')
    op.drop_index(op.f('ix_therapy_summaries_student_id'), table_name='therapy_summaries')
    op.drop_index(op.f('ix_therapy_summaries_reports_hash'), table_name='therapy_summaries')
    op.drop_index(op.f('ix_therapy_summaries_id'), table_name='therapy_summaries')
    op.drop_table('therapy_summaries')
    # ### end Alembic commands ###
