"""add_used_reports_to_therapy_summaries

Revision ID: 5b1f158f9389
Revises: 42c93e13d04e
Create Date: 2026-06-28 16:07:34.086716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_used_reports_to_therapy_summaries

Revision ID: 5b1f158f9389
Revises: 42c93e13d04e
Create Date: 2026-06-28 16:07:34.086716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b1f158f9389'
down_revision: Union[str, None] = '42c93e13d04e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('therapy_summaries', sa.Column('used_reports', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('therapy_summaries', 'used_reports')
    # ### end Alembic commands ###
