"""add development_history_items to students

Revision ID: 74e78d266220
Revises: 9999abcd1234
Create Date: 2026-05-28 06:59:59.233161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74e78d266220'
down_revision: Union[str, None] = '9999abcd1234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_therapy_reports_student_id', table_name='therapy_reports')
    op.drop_index('ix_therapy_reports_teacher_id', table_name='therapy_reports')
    op.drop_table('therapy_reports')
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.add_column('students', sa.Column('development_history_items', sa.Text(), nullable=True))
    op.drop_column('students', 'class_teacher')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('class_teacher', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('students', 'development_history_items')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_table('therapy_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('report_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('therapy_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('progress_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('goals_achieved', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('progress_level', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('present_complaints', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('current_observation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('assessment_done', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('provisional_diagnosis', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='therapy_reports_student_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name='therapy_reports_teacher_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='therapy_reports_pkey')
    )
    op.create_index('ix_therapy_reports_teacher_id', 'therapy_reports', ['teacher_id'], unique=False)
    op.create_index('ix_therapy_reports_student_id', 'therapy_reports', ['student_id'], unique=False)
    # ### end Alembic commands ###
